spring.application.name=Bike Shop Order Tracker
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/bike_shop_order_tracker?createDatabaseIfNotExist=true&serverTimezone=UTC}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:[YOUR-USERNAME]}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:[YOUR-PASSWORD]}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=5

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
logging.level.com.gcu.bikeshop=INFO
